name: PR Create Action

on:
  push:
    branches:
      - study/*
      
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set Date
        id: set_param 
        run: |
          date=$(TZ=Asia/Seoul date +'%Y%m%d')
          TITLE="$date ${{ github.actor }}"
          echo "title=$TITLE" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: ${{ steps.set_param.outputs.title }}
          base: main