name: PR Create Action

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - study/*
      - cs/*
      - db/*
      - comm/*
      - algo/*
      - work/*
      - proj/*
      
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: set date
        id: set_param 
        run: |
          date=$(TZ=Asia/Seoul date +'%Y%m%d')
          TITLE="$date ${{ github.actor }}"
          echo "title=$TITLE" >> $GITHUB_OUTPUT

      - name: pr create use gh cli
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head "${GITHUB_REF#refs/heads/}" \
            --title "${{ steps.set_param.outputs.title }}" \
            --body-file  .github/pull_request_template.md

      - name: pr labels update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if : ${{ !contains(github.ref_name, 'study') }}
        run: |
          type=$(echo "${GITHUB_REF#refs/heads/study/}" | cut -d'/' -f1)
          if [ "$type" = "cs" ]; then
            gh pr edit  --add-label "Computer Science"
          elif [ "$type" = "db" ]; then
            gh pr edit  --add-label "DB/SQL"
          elif [ "$type" = "comm" ]; then
            gh pr edit  --add-label "Communication"
          elif [ "$type" = "algo" ]; then
            gh pr edit  --add-label "알고리즘/자료구조
          elif [ "$type" = "work" ]; then
            gh pr edit  --add-label "업무"
          elif [ "$type" = "proj" ]; then
            gh pr edit  --add-label "프로젝트"
          else
            echo "No specific label for type: $type"
          fi