name: PR Create Action

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - study/*
      - cs/*
      - db/*
      - comm/*
      - algo/*
      - work/*
      - proj/*
      - lic/*
      
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: set date
        id: set_param 
        run: |
          date=$(TZ=Asia/Seoul date +'%Y%m%d')
          actor="${{ github.actor }}"
          if [ -z "$actor" ]; then
            actor="${{ github.event.pusher.name }}"
          fi
          if [ -z "$actor" ]; then
            actor="unknown-user"
          fi
          TITLE="$date $actor"
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "actor=$actor" >> $GITHUB_OUTPUT

      - name: check diff with main
        id: diff_check
        run: |
          git fetch origin main
          if git diff --quiet origin/main...HEAD; then
            echo "no_diff=true" >> $GITHUB_OUTPUT
          else
            echo "no_diff=false" >> $GITHUB_OUTPUT
          fi
          
      - name: pr create use gh cli
        if: steps.diff_check.outputs.no_diff == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head "${GITHUB_REF#refs/heads/}" \
            --title "${{ steps.set_param.outputs.title }}" \
            --body-file  .github/pull_request_template.md \
            --assignee "${{ steps.set_param.outputs.actor }}"

      - name: pr labels update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.diff_check.outputs.no_diff == 'false' && !contains(github.ref_name, 'study')
        run: |
          type=$(echo "${GITHUB_REF#refs/heads/}" | cut -d'/' -f1)
          if [ "$type" = "cs" ]; then
            gh pr edit  --add-label "Computer Science"
          elif [ "$type" = "db" ]; then
            gh pr edit  --add-label "DB/SQL"
          elif [ "$type" = "comm" ]; then
            gh pr edit  --add-label "커뮤니케이션"
          elif [ "$type" = "algo" ]; then
            gh pr edit  --add-label "알고리즘/자료구조"
          elif [ "$type" = "work" ]; then
            gh pr edit  --add-label "업무"
          elif [ "$type" = "proj" ]; then
            gh pr edit  --add-label "프로젝트"
          elif [ "$type" = "lic" ]; then
            gh pr edit  --add-label "자격증"
          else
            echo "No specific label for type: $type"
          fi
